workflows:
  react-native-android:
    name: Build APK for Clippr-d
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "com.clipprd"
        ANDROID_SDK_ROOT: $HOME/Library/Android/sdk
      node: 16.20.0
      java: 11
      android_signing:
        - clipprd_keystore
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "*"
          include: true
    scripts:
      - name: Install Dependencies
        script: |
          npm install
      - name: Install Android SDK Platform
        script: |
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"
      - name: Build Release APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - lohanmangaka@gmail.com
        notify:
          success: true
          failure: true
