workflows:
  react-native-android:
    name: Build APK for Clippr-d
    max_build_duration: 60
    environment:
      vars:
        NODE_ENV: production
      android_signing:
        keystore_reference: clipprd_keystore
      flutter: stable
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
